#!/bin/bash

prev=a

while ((1))
do
	if [[ -e log.txt ]]
	then
		cur=$( tail -n 1 log.txt )
		if [[ $cur != $prev ]] 
		then
			if [[ $cur =~ ^-?[[:digit:]]+$ ]]
			then
				echo $cur
			else
				echo "Spoiler Alert!"
			fi
			prev=$cur
		fi
	fi
done
